version: 2.1

jobs:
  validate:
    docker:
      - image: cimg/openjdk:16.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean install
      - run:
          name: Run tests
          command: mvn test
  push:
    machine:
      image: cimg/base:2025.01
    steps:
      - checkout
      - run:
          name: Install Docker BuildX for Multi-architecture builds
          command: |
            mkdir -vp ~/.docker/cli-plugins/
            curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker buildx version
            sudo apt-get update && sudo apt-get install -y binfmt-support qemu-user-static
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker run --privileged --rm tonistiigi/binfmt --install arm64
            docker context create buildcontext
            docker buildx create buildcontext --use
      - run:
          name: Quay.io Login
          command: docker login -u="${QUAYIO_USERNAME}" -p="${QUAYIO_PASSWORD}" quay.io
      - run:
          name: Tag and Push
          command: |
            DATE=$(date '+%Y-%m-%d')
            SHORT_SHA1=$(echo $CIRCLE_SHA1 | cut -c1-7)
            VERSION=${DATE}.${CIRCLE_BUILD_NUM}.${SHORT_SHA1}
            docker buildx build -t "quay.io/hmpps/${CIRCLE_PROJECT_REPONAME}:latest" -t "quay.io/hmpps/${CIRCLE_PROJECT_REPONAME}:${VERSION}" --platform linux/amd64,linux/arm64 . --push

workflows:
  build:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - push:
          requires:
            - validate
          filters:
            branches:
              only:
                - main
